import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";import vm from "node:vm";import ts from "typescript";import{createRequire}from"node:module";
const source=fs.readFileSync(new URL("../app/diagnostic-engine.ts",import.meta.url),"utf8"),js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,require=createRequire(import.meta.url),mod={exports:{}},sandbox={module:mod,exports:mod.exports,require,Set,Map,Object,Math};vm.createContext(sandbox);vm.runInContext(js,sandbox);const{CORE_QUESTIONS,evaluateDiagnostic,buildQuestionPath,buildClientStartingPoint}=mod.exports;const a=x=>x.map(([questionId,optionId])=>({questionId,optionId}));
const healthy=[["goal","leads"],["direction","clear"],["audience","clear"],["offer","clear"],["message","clear"],["reach","steady"],["conversion","clear"],["management","routine_measured"]];const run=changes=>evaluateDiagnostic(a(healthy.map(([q,v])=>[q,changes[q]||v])));
test("שמונה תחומים ושמונה שאלות ליבה",()=>{assert.equal(CORE_QUESTIONS.length,8);assert.equal(new Set(CORE_QUESTIONS.map(q=>q.id)).size,8)});
test("A בסיס תקין ומחסור בחשיפה",()=>assert.equal(run({goal:"awareness",reach:"none"}).primary,"REACH"));
test("B חוסר מטרה ופוקוס",()=>assert.equal(run({goal:"order",direction:"unknown",offer:"many"}).primary,"DIRECTION"));
test("C פניות לא מתאימות פוסלות חשיפה",()=>{const r=run({audience:"bad_fit",reach:"unstable"});assert.equal(r.primary,"AUDIENCE");assert.ok(r.excluded.some(x=>x.area==="REACH"))});
test("D הצעה עמומה",()=>assert.equal(run({offer:"generic"}).primary,"OFFER"));
test("E מסר מפוזר עם חשיפה",()=>assert.equal(run({message:"scattered",reach:"steady"}).primary,"MESSAGE"));
test("F עניין עם דליפה אחרי פנייה",()=>assert.equal(run({conversion:"lost"}).primary,"CONVERSION"));
test("G כיוון ברור ללא קיבולת",()=>assert.equal(run({goal:"consistency",management:"clear_no_capacity"}).primary,"CAPACITY"));
test("H ביצוע ללא מדידה",()=>assert.equal(run({management:"routine_unknown"}).primary,"MEASUREMENT"));
test("I תיקו אמיתי אינו מקבל ודאות גבוהה",()=>{const r=run({management:"no_routine_no_data"});assert.equal(r.confidence,"INSUFFICIENT");assert.equal(r.primary,null)});
test("חוסר בהירות קודם לעומס",()=>assert.equal(run({direction:"unknown",management:"too_much"}).primary,"DIRECTION"));
test("מסלול ציבורי מוגבל לעשר שאלות",()=>{const path=buildQuestionPath(a(healthy));assert.ok(path.length<=2);assert.ok(8+path.length<=10)});
test("פלט מקצועי ותשתית לקוח מלאים",()=>{const r=run({message:"scattered"}),c=buildClientStartingPoint(r);assert.equal(r.actionMap.length,3);assert.equal(r.workPlanSeed.first30.length,4);assert.equal(c.first30Days.length,4);assert.ok(c.questionsToValidateInMeeting.length>=3)});
test("אין מקף ארוך בטקסטי המנוע",()=>assert.doesNotMatch(source,/—/));
