import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
import ts from "typescript";
import { createRequire } from "node:module";

const source=fs.readFileSync(new URL("../app/diagnostic-engine.ts",import.meta.url),"utf8");
const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
const require=createRequire(import.meta.url),testModule={exports:{}},sandbox={module:testModule,exports:testModule.exports,require,structuredClone,Set,Map,Object,Math};
vm.createContext(sandbox);vm.runInContext(js,sandbox);
const{evaluateDiagnostic,CORE_QUESTIONS,buildQuestionPath}=testModule.exports;
const a=pairs=>pairs.map(([questionId,optionId])=>({questionId,optionId}));

test("קיים מקור אמת אחד ובו שבע שאלות ליבה",()=>{assert.equal(CORE_QUESTIONS.length,7);assert.equal(new Set(CORE_QUESTIONS.map(q=>q.id)).size,7);assert.ok(CORE_QUESTIONS.every(q=>q.options.length<=6));assert.doesNotMatch(fs.readFileSync(new URL("../app/page.tsx",import.meta.url),"utf8"),/legacyQuestions/)});
test("אין כיוון ברור מחזיר כיוון",()=>{const r=evaluateDiagnostic(a([["goal","order"],["focus","unsure"],["audience","clear"],["response","good"],["message","clear"],["acquisition","steady"],["capacity","dont_know"]]));assert.equal(r.primaryBottleneck,"DIRECTION")});
test("יש כיוון אך הקהל רחב והפניות לא מתאימות מחזיר קהל והצעה",()=>{const r=evaluateDiagnostic(a([["goal","more_leads"],["focus","clear"],["audience","broad"],["response","bad_leads"],["message","clear"],["acquisition","steady"],["capacity","consistent"]]));assert.equal(r.primaryBottleneck,"AUDIENCE_OFFER");assert.equal(r.statuses.REACH.eligibleForPrimary,false)});
test("יש חשיפה אך מעט עניין ותוכן מפוזר מחזיר מסר ותוכן",()=>{const r=evaluateDiagnostic(a([["goal","more_leads"],["focus","clear"],["audience","clear"],["response","no_response"],["message","scattered"],["acquisition","steady"],["capacity","what_post"]]));assert.equal(r.primaryBottleneck,"MESSAGE_CONTENT")});
test("יש עניין אך הדרך לפנייה לא ברורה מחזיר מסלול פנייה",()=>{const r=evaluateDiagnostic(a([["goal","more_leads"],["focus","clear"],["audience","clear"],["response","interest_low_action"],["message","clear"],["acquisition","steady"],["capacity","consistent"],["conversion_check","unclear"]]));assert.equal(r.primaryBottleneck,"CONVERSION_PATH");assert.equal(r.subtype,"PRE_LEAD_FRICTION")});
test("כשהבסיס ברור ואין מקור קבוע לקהל חדש מתקבלת חשיפה",()=>{const r=evaluateDiagnostic(a([["goal","recognition"],["focus","clear"],["audience","clear"],["response","unknown"],["message","clear"],["acquisition","none"],["capacity","consistent"]]));assert.equal(r.primaryBottleneck,"REACH")});
test("כשברור מה לעשות אך אין התמדה מתקבלת יכולת ביצוע",()=>{const r=evaluateDiagnostic(a([["goal","sustain"],["focus","clear"],["audience","clear"],["response","good"],["message","clear"],["acquisition","steady"],["capacity","no_time"]]));assert.equal(r.primaryBottleneck,"CAPACITY")});
test("חוסר זמן שנובע מחוסר בהירות מחזיר כיוון לפני יכולת ביצוע",()=>{const r=evaluateDiagnostic(a([["goal","sustain"],["focus","several"],["audience","clear"],["response","good"],["message","mostly"],["acquisition","steady"],["capacity","dont_know"]]));assert.equal(r.primaryBottleneck,"DIRECTION")});
test("הרבה תשובות לא ידועות מחזירות שאין מספיק מידע",()=>{const r=evaluateDiagnostic(a([["goal","more_leads"],["focus","clear"],["audience","broad"],["response","unknown"],["message","unknown"],["acquisition","unknown"],["capacity","consistent"]]));assert.equal(r.primaryBottleneck,"INSUFFICIENT_EVIDENCE");assert.equal(r.confidence,"INSUFFICIENT")});
test("תשובות סותרות אינן מקבלות ודאות גבוהה",()=>{const r=evaluateDiagnostic(a([["goal","recognition"],["focus","clear"],["audience","broad"],["response","good"],["message","scattered"],["acquisition","none"],["capacity","consistent"]]));assert.notEqual(r.confidence,"HIGH")});
test("שאלת הסתעפות מופיעה רק כשצריך ומספר השאלות הכולל נשאר קצר",()=>{const clear=a([["goal","order"],["focus","unsure"],["audience","clear"],["response","good"],["message","clear"],["acquisition","steady"],["capacity","dont_know"]]);assert.equal(buildQuestionPath(clear).length,0);const close=a([["goal","more_leads"],["focus","clear"],["audience","broad"],["response","interest_low_action"],["message","mostly"],["acquisition","content_unstable"],["capacity","consistent"]]);const path=buildQuestionPath(close);assert.ok(path.length>=1&&path.length<=2);assert.ok(7+path.length<=9)});
test("הפלט המקצועי מכיל ראיות, נקודת התחלה ומפת פעולה",()=>{const r=evaluateDiagnostic(a([["goal","order"],["focus","unsure"],["audience","clear"],["response","good"],["message","clear"],["acquisition","steady"],["capacity","dont_know"]]));assert.ok(r.diagnosticDetail.evidence.length>=2);assert.ok(r.diagnosticDetail.recommendedStartingPoint.length>=3);assert.deepEqual(Object.keys(r.diagnosticDetail.actionMap),["check","decide","implement"]);assert.ok(Object.values(r.diagnosticDetail.actionMap).every(text=>text.length>20));assert.equal(r.questionsAsked.length,7)});
test("נוסח שבע שאלות הליבה חד, קצר וממוקד",()=>{assert.equal(CORE_QUESTIONS[0].title,"מה הכי היית רוצה שיקרה בשיווק שלך בחודשיים הקרובים?");assert.equal(CORE_QUESTIONS[1].title,"עד כמה ברור לך מה את רוצה לקדם עכשיו?");assert.equal(CORE_QUESTIONS[4].title,"עד כמה ברור מהשיווק שלך מה את מציעה ולמי זה מתאים?")});
test("טקסטי השאלון נקיים ממונחי מנוע וממקף ארוך",()=>{const paths=[];for(const q of CORE_QUESTIONS)for(const op of q.options){const baseline=CORE_QUESTIONS.map(x=>({questionId:x.id,optionId:x.options[0].id}));baseline[CORE_QUESTIONS.indexOf(q)]={questionId:q.id,optionId:op.id};paths.push(...buildQuestionPath(baseline))}const questions=new Map([...CORE_QUESTIONS,...paths].map(q=>[q.id,q]));const forbidden=/—|\b(?:Direction|Capacity|Audience|Offer|Message|Content|Conversion|Reach|Primary|Secondary|Scoring)\b|Rule Engine|Follow-up/i;for(const q of questions.values())for(const text of[q.eyebrow,q.title,...q.options.map(o=>o.label)])assert.equal(forbidden.test(text),false,text)});
