export const DIAGNOSTIC_AREAS = ["DIRECTION", "AUDIENCE", "OFFER", "MESSAGE", "REACH", "CONVERSION", "CAPACITY", "MEASUREMENT"] as const;
export type DiagnosticArea = (typeof DIAGNOSTIC_AREAS)[number];
export type Confidence = "HIGH" | "MEDIUM" | "INSUFFICIENT";
export type AnswerRecord = { questionId: string; optionId: string };
export type EvidenceItem = { area: DiagnosticArea; text: string };
export type Option = { id: string; label: string; scores?: Partial<Record<DiagnosticArea, number>>; supports?: DiagnosticArea[]; contradicts?: DiagnosticArea[]; excludes?: DiagnosticArea[]; evidence?: string; unknown?: boolean; facts?: string[] };
export type Question = { id: string; stage: "מטרה" | "סריקה" | "מיקוד"; title: string; options: Option[]; core?: boolean };
export type ActionStep = { title: string; body: string; task: string };
export type DiagnosticResult = {
  mode: "PUBLIC"; primary: DiagnosticArea | null; secondary: DiagnosticArea | null; confidence: Confidence;
  headline: string; oneLineDiagnosis: string; evidence: EvidenceItem[]; contradictions: EvidenceItem[];
  impact: string; focusNow: string; avoidNow: string[]; actionMap: ActionStep[]; firstActionToday: string;
  secondaryNote?: string; recommendedStartingPoint: string[];
  strategySeed: Record<"positioning" | "audience" | "offer" | "message" | "channels" | "conversion" | "capacity" | "measurement", boolean>;
  workPlanSeed: { first30: string[]; next60: string[]; postpone: string[] };
  questionsAsked: string[]; answers: AnswerRecord[]; candidates: DiagnosticArea[];
  excluded: { area: DiagnosticArea; reason: string }[]; scores: Record<DiagnosticArea, number>;
};
export type ClientStartingPoint = { diagnosisSummary: string; questionsToValidateInMeeting: string[]; recommendedWorkOrder: string[]; first30Days: string[]; next60Days: string[]; inputsNeededFromClient: string[]; strategySectionsToBuild: string[] };

export const AREA_LABELS: Record<DiagnosticArea, string> = { DIRECTION:"כיוון", AUDIENCE:"קהל", OFFER:"הצעה", MESSAGE:"מסר", REACH:"חשיפה", CONVERSION:"המרה", CAPACITY:"יכולת ביצוע", MEASUREMENT:"מדידה" };
const o=(id:string,label:string,x:Omit<Option,"id"|"label">={}):Option=>({id,label,...x});

export const CORE_QUESTIONS: Question[] = [
 {id:"goal",core:true,stage:"מטרה",title:"מה הכי חשוב לך שיקרה בשיווק בחודשיים הקרובים?",options:[o("awareness","להגיע ליותר אנשים נכונים",{scores:{REACH:8}}),o("leads","לקבל יותר פניות",{scores:{CONVERSION:7,MESSAGE:3}}),o("clients","להפוך יותר פניות ללקוחות",{scores:{CONVERSION:9}}),o("order","לעשות סדר ולהבין במה להתמקד",{scores:{DIRECTION:12},supports:["DIRECTION"],evidence:"המטרה המרכזית כרגע היא ליצור סדר ומיקוד"}),o("consistency","להתמיד בלי להישחק",{scores:{CAPACITY:12},supports:["CAPACITY"],evidence:"הצורך המרכזי הוא ליצור שיווק שאפשר להתמיד בו"})]},
 {id:"direction",core:true,stage:"סריקה",title:"עד כמה ברור לך מה המטרה השיווקית המרכזית ומה מקדמים עכשיו?",options:[o("clear","ברור מאוד. יש מטרה והצעה מרכזית",{scores:{DIRECTION:-24},contradicts:["DIRECTION"],excludes:["DIRECTION"],facts:["direction_ok","execution_clear"],evidence:"יש מטרה ברורה והצעה מרכזית"}),o("partial","יש כיוון, אבל יותר מדי דברים מתחרים על תשומת הלב",{scores:{DIRECTION:22},supports:["DIRECTION"],facts:["direction_bad","execution_unclear"],evidence:"כמה מטרות מתחרות על תשומת הלב"}),o("changes","המיקוד משתנה לעיתים קרובות",{scores:{DIRECTION:27},supports:["DIRECTION"],facts:["direction_bad","execution_unclear"],evidence:"המיקוד השיווקי משתנה לעיתים קרובות"}),o("unknown","לא ברור לי מה נכון לקדם",{scores:{DIRECTION:30},supports:["DIRECTION"],facts:["direction_bad","execution_unclear"],evidence:"לא ברור מה נכון לקדם"})]},
 {id:"audience",core:true,stage:"סריקה",title:"עד כמה ברור לך מי הקהל המדויק שאת רוצה למשוך?",options:[o("clear","ברור מאוד, וגם הפניות בדרך כלל מתאימות",{scores:{AUDIENCE:-24,REACH:-14},contradicts:["AUDIENCE","REACH"],excludes:["AUDIENCE"],facts:["audience_ok"],evidence:"הקהל מוגדר והפניות בדרך כלל מתאימות"}),o("broad","יש כיוון, אבל הקהל עדיין רחב",{scores:{AUDIENCE:22},supports:["AUDIENCE"],facts:["audience_bad"],evidence:"הגדרת הקהל עדיין רחבה"}),o("bad_fit","מגיעות פניות, אבל רבות מהן לא מתאימות",{scores:{AUDIENCE:30,REACH:-30},supports:["AUDIENCE"],contradicts:["REACH"],excludes:["REACH"],facts:["audience_bad","leads_exist"],evidence:"מגיעות פניות שאינן מתאימות מספיק"}),o("unknown","אני עדיין לא יודעת למי נכון לפנות",{scores:{AUDIENCE:27},supports:["AUDIENCE"],facts:["audience_bad"],evidence:"לא ברור מספיק למי נכון לפנות"})]},
 {id:"offer",core:true,stage:"סריקה",title:"עד כמה ההצעה שלך ברורה, ממוקדת וקלה להבנה?",options:[o("clear","ברורה וממוקדת",{scores:{OFFER:-24},contradicts:["OFFER"],excludes:["OFFER"],facts:["offer_ok"],evidence:"ההצעה ברורה וממוקדת"}),o("many","יש כמה הצעות וקשה לדעת מה להוביל",{scores:{OFFER:25,DIRECTION:6},supports:["OFFER"],facts:["offer_bad"],evidence:"כמה הצעות מתחרות על המקום המרכזי"}),o("explain","נדרש הרבה הסבר כדי להבין את הערך",{scores:{OFFER:24,MESSAGE:7},supports:["OFFER"],facts:["offer_bad"],evidence:"נדרש הסבר רב כדי להבין את ערך ההצעה"}),o("generic","ההצעה מרגישה כללית או דומה לאחרות",{scores:{OFFER:27},supports:["OFFER"],facts:["offer_bad"],evidence:"ההצעה עדיין כללית ולא מובחנת"})]},
 {id:"message",core:true,stage:"סריקה",title:"כשמישהי פוגשת את השיווק שלך, עד כמה ברור לה מה את מציעה ולמה זה רלוונטי לה?",options:[o("clear","ברור מאוד ונוצר עניין",{scores:{MESSAGE:-24},contradicts:["MESSAGE"],excludes:["MESSAGE"],facts:["message_ok","interest"],evidence:"המסר ברור ומעורר עניין"}),o("mixed","חלק מהתוכן ברור וחלק פחות",{scores:{MESSAGE:18},supports:["MESSAGE"],facts:["message_bad"],evidence:"המסר אינו עקבי בכל נקודות המפגש"}),o("scattered","התוכן מפוזר בין נושאים רבים",{scores:{MESSAGE:27,DIRECTION:5},supports:["MESSAGE"],facts:["message_bad"],evidence:"התוכן מפוזר בין מסרים רבים"}),o("low_interest","יש חשיפה, אבל כמעט שאין עניין או תגובה",{scores:{MESSAGE:29,AUDIENCE:8},supports:["MESSAGE"],facts:["message_bad","no_interest","reach_exists"],evidence:"יש חשיפה אך כמעט שאין עניין"})]},
 {id:"reach",core:true,stage:"סריקה",title:"עד כמה יש לך דרך קבועה להגיע לקהל חדש ורלוונטי?",options:[o("steady","יש ערוץ אחד או יותר שעובדים בקביעות",{scores:{REACH:-25},contradicts:["REACH"],excludes:["REACH"],facts:["reach_ok","reach_exists"],evidence:"קיים ערוץ קבוע שמביא קהל חדש"}),o("referrals","רוב הלקוחות מגיעים מהמלצות",{scores:{REACH:19},supports:["REACH"],facts:["reach_bad"],evidence:"רוב הלקוחות מגיעים מהמלצות בלבד"}),o("unstable","יש חשיפה, אבל היא אינה יציבה",{scores:{REACH:18},supports:["REACH"],facts:["reach_bad","reach_exists"],evidence:"החשיפה קיימת אך אינה יציבה"}),o("none","כמעט שאין דרך קבועה להגיע לקהל חדש",{scores:{REACH:30},supports:["REACH"],facts:["reach_bad"],evidence:"אין מנגנון קבוע להגעה לקהל חדש"})]},
 {id:"conversion",core:true,stage:"סריקה",title:"מה קורה כשמישהי כבר מתעניינת או פונה?",options:[o("clear","הדרך לפנייה ברורה והפניות מטופלות באופן מסודר",{scores:{CONVERSION:-25},contradicts:["CONVERSION"],excludes:["CONVERSION"],facts:["conversion_ok"],evidence:"הדרך לפנייה והטיפול בה ברורים"}),o("few_act","יש עניין, אבל מעט ממשיכות לפעולה",{scores:{CONVERSION:27},supports:["CONVERSION"],facts:["interest","conversion_bad","prelead"],evidence:"יש עניין, אך מעט ממשיכות לפעולה"}),o("unclear_cta","לא תמיד ברור מה הצעד הבא",{scores:{CONVERSION:25},supports:["CONVERSION"],facts:["conversion_bad","prelead"],evidence:"הצעד הבא בדרך לפנייה אינו ברור"}),o("lost","פניות נכנסות, אבל הטיפול והמעקב אינם עקביים",{scores:{CONVERSION:31},supports:["CONVERSION"],facts:["conversion_bad","postlead","leads_exist"],evidence:"פניות נכנסות אך הטיפול והמעקב אינם עקביים"})]},
 {id:"management",core:true,stage:"סריקה",title:"מה מתאר הכי טוב את היכולת שלך לבצע ולדעת מה עובד?",options:[o("routine_measured","יש לי שגרת ביצוע ואני יודעת מה מביא תוצאות",{scores:{CAPACITY:-24,MEASUREMENT:-24},contradicts:["CAPACITY","MEASUREMENT"],excludes:["CAPACITY","MEASUREMENT"],facts:["capacity_ok","measurement_ok"],evidence:"יש שגרת ביצוע ומעקב אחר תוצאות"}),o("clear_no_capacity","ברור לי מה לעשות, אבל אין לי זמן או קיבולת לבצע",{scores:{CAPACITY:31},supports:["CAPACITY"],facts:["capacity_bad","execution_clear"],evidence:"הכיוון ברור, אך אין קיבולת לבצע"}),o("too_much","אני מנסה לעשות יותר מדי ולא מצליחה להתמיד",{scores:{CAPACITY:24,DIRECTION:7},supports:["CAPACITY"],facts:["capacity_bad"],evidence:"היקף הפעולות מקשה על התמדה"}),o("routine_unknown","אני מבצעת, אבל לא באמת יודעת מה עובד",{scores:{MEASUREMENT:31},supports:["MEASUREMENT"],facts:["measurement_bad","capacity_ok"],evidence:"יש ביצוע, אבל אין תמונה ברורה של מה עובד"}),o("no_routine_no_data","אין שגרה קבועה וגם אין לי מספיק נתונים",{scores:{CAPACITY:20,MEASUREMENT:20},supports:["CAPACITY","MEASUREMENT"],facts:["capacity_bad","measurement_bad"],evidence:"אין שגרת ביצוע ואין מספיק נתונים"}),o("unknown","קשה לי לדעת",{unknown:true,facts:["missing"]})]}
];

const DECISION_QUESTIONS: Record<string,Question> = {};
function decision(a:DiagnosticArea,b:DiagnosticArea,q:Question){DECISION_QUESTIONS[[a,b].sort().join("|")]=q}
decision("DIRECTION","OFFER",{id:"decide_direction_offer",stage:"מיקוד",title:"מה קורה קודם כשאת מנסה לתכנן שיווק?",options:[o("direction","קשה לבחור מטרה אחת ולכן גם ההצעה משתנה",{scores:{DIRECTION:18,OFFER:-5},supports:["DIRECTION"],evidence:"חוסר החלטה על המטרה גורם להצעה להשתנות"}),o("offer","המטרה ברורה, אבל ההצעה עצמה עדיין לא חדה",{scores:{OFFER:18,DIRECTION:-5},supports:["OFFER"],evidence:"המטרה ברורה, אך ההצעה אינה חדה"})]});
decision("AUDIENCE","MESSAGE",{id:"decide_audience_message",stage:"מיקוד",title:"מה נראה שקורה אצל מי שנחשפת לשיווק שלך?",options:[o("audience","המסר מובן, אבל הוא מגיע לאנשים הלא נכונים",{scores:{AUDIENCE:18,MESSAGE:-5},supports:["AUDIENCE"],evidence:"המסר מגיע לקהל שאינו מתאים"}),o("message","הקהל נכון, אבל המסר לא יוצר מספיק עניין",{scores:{MESSAGE:18,AUDIENCE:-5},supports:["MESSAGE"],evidence:"הקהל נכון, אך המסר אינו יוצר עניין"})]});
decision("MESSAGE","CONVERSION",{id:"decide_message_conversion",stage:"מיקוד",title:"כשיש מעט פעולה, מה מתאר טוב יותר את המצב?",options:[o("message","לא נוצר מספיק רצון או חיבור מלכתחילה",{scores:{MESSAGE:18,CONVERSION:-4},supports:["MESSAGE"],evidence:"המסר אינו יוצר מספיק רצון"}),o("conversion","יש רצון להתקדם, אבל הדרך לפנייה אינה ברורה",{scores:{CONVERSION:18,MESSAGE:-6},supports:["CONVERSION"],facts:["interest"],evidence:"יש רצון, אך הדרך לפנייה אינה ברורה"})]});
decision("DIRECTION","CAPACITY",{id:"decide_direction_capacity",stage:"מיקוד",title:"מה בעיקר מונע ממך לבצע באופן עקבי?",options:[o("direction","לא ברור לי מה באמת חשוב לעשות קודם",{scores:{DIRECTION:19,CAPACITY:-4},supports:["DIRECTION"],facts:["execution_unclear"],evidence:"חוסר בהירות מונע ביצוע עקבי"}),o("capacity","ברור לי בדיוק מה לעשות, אבל אין קיבולת לכך",{scores:{CAPACITY:19,DIRECTION:-5},supports:["CAPACITY"],facts:["execution_clear"],evidence:"הכיוון ברור, אך אין קיבולת לבצע"})]});
decision("CAPACITY","MEASUREMENT",{id:"decide_capacity_measurement",stage:"מיקוד",title:"מה יעזור לך יותר לקבל החלטה טובה כבר השבוע?",options:[o("capacity","לפנות זמן ולצמצם את היקף המשימות",{scores:{CAPACITY:17},supports:["CAPACITY"],evidence:"נדרש קודם לצמצם עומס ולפנות קיבולת"}),o("measurement","לקבל תמונה אמינה של מה עובד ומה לא",{scores:{MEASUREMENT:17},supports:["MEASUREMENT"],evidence:"נדרשת קודם תמונה אמינה של הביצועים"})]});

const COPY: Record<DiagnosticArea,{headline:string;diagnosis:string;impact:string;focus:string;avoid:string[];steps:ActionStep[];today:string;first30:string[];next60:string[]}> = {
 DIRECTION:{headline:"הכיוון עדיין לא מספיק חד",diagnosis:"הבעיה אינה מחסור ברעיונות, אלא קושי להחליט מה באמת מוביל את השיווק עכשיו.",impact:"כשאין מטרה אחת והצעה מרכזית, כל פעולה מושכת לכיוון אחר. התוכן מתפזר, הביצוע מעמיס וקשה לדעת מה עובד.",focus:"לבחור מטרה עסקית אחת והצעה מרכזית אחת לחודשיים הקרובים.",avoid:["לא לפתוח ערוץ חדש","לא לקדם כמה הצעות במקביל","לא לבנות עוד תוכן לפני בחירת המיקוד"],steps:[{title:"ממפות",body:"בודקות אילו מטרות והצעות מתחרות כרגע.",task:"רשמי את כל מה שאת מנסה לקדם"},{title:"בוחרות",body:"מחליטות על תוצאה אחת והצעה אחת.",task:"סמני יעד אחד ל־60 הימים הקרובים"},{title:"מיישמות",body:"מחברות את כל הפעולות לבחירה.",task:"הסירי השבוע פעולה אחת שלא משרתת את היעד"}],today:"כתבי במשפט אחד איזו תוצאה עסקית אחת השיווק צריך לייצר בחודשיים הקרובים.",first30:["שבוע 1: בחירת מטרה והצעה מרכזית","שבוע 2: ניסוח סדר עדיפויות","שבוע 3: חיבור התוכן למיקוד","שבוע 4: בדיקת התקדמות"],next60:["להעמיק במסר המרכזי","להרחיב רק מה שמשרת את היעד"]},
 AUDIENCE:{headline:"השיווק פוגש קהל רחב מדי",diagnosis:"האתגר המרכזי הוא דיוק הקהל, כדי שהשיווק ימשוך יותר מהפניות שבאמת מתאימות לעסק.",impact:"כאשר הקהל רחב, גם מסר טוב מתקשה להרגיש אישי ורלוונטי. התוצאה היא יותר מאמץ, פניות פחות מתאימות וקושי לחדד את ההצעה.",focus:"להגדיר מי הלקוחה שהכי מתאימה להצעה ולמה היא מחפשת פתרון עכשיו.",avoid:["לא להגדיל חשיפה לקהל רחב","לא לנסות לדבר לכולן","לא לשנות את כל ההצעה בבת אחת"],steps:[{title:"ממפות",body:"בודקות מי הפכה ללקוחה טובה ומי לא התאימה.",task:"בחרי שלוש פניות טובות מהתקופה האחרונה"},{title:"מחדדות",body:"מזהות צורך, הקשר וסימני התאמה.",task:"כתבי מה היה משותף לפניות הטובות"},{title:"מתאימות",body:"מעדכנות את המסר כך שהקהל הנכון יזהה את עצמו.",task:"הוסיפי למסך הראשי משפט התאמה אחד"}],today:"בחרי שלוש לקוחות טובות וכתבי מה היה משותף להן ברגע שבו פנו.",first30:["שבוע 1: ניתוח פניות ולקוחות","שבוע 2: הגדרת קהל מדויק","שבוע 3: התאמת ההצעה והמסר","שבוע 4: בדיקת איכות הפניות"],next60:["לבנות תכנים לקהל המדויק","לבדוק איכות פניות לאורך זמן"]},
 OFFER:{headline:"ההצעה דורשת יותר מדי הסבר",diagnosis:"הערך קיים, אבל ההצעה עדיין אינה מספיק ממוקדת וקלה להבנה ברגע הראשון.",impact:"כשההצעה רחבה או מורכבת, הקהל צריך לעבוד קשה כדי להבין אם היא מתאימה לו. גם מסר טוב וחשיפה גבוהה לא יפצו על עמימות בנקודה הזאת.",focus:"לנסח הצעה אחת עם תוצאה ברורה, קהל ברור וסיבה טובה לבחור בה עכשיו.",avoid:["לא להוסיף עוד שירותים","לא להעמיס פרטים על הכותרת","לא להתחיל קמפיין לפני החידוד"],steps:[{title:"מזקקות",body:"מפרידות בין השירות לבין התוצאה שהלקוחה מחפשת.",task:"כתבי מה משתנה אצל הלקוחה אחרי העבודה"},{title:"בונות",body:"מנסחות הצעה פשוטה ומובחנת.",task:"נסחי קהל, צורך ותוצאה במשפט אחד"},{title:"בודקות",body:"מוודאות שההצעה מובנת בלי הסבר נוסף.",task:"הראי את המשפט לשתי לקוחות עבר"}],today:"נסחי את ההצעה במשפט אחד: למי היא, מה היא פותרת ומה משתנה בעקבותיה.",first30:["שבוע 1: זיקוק התוצאה","שבוע 2: בניית הצעה מרכזית","שבוע 3: בדיקת הבנה","שבוע 4: עדכון נקודות המפגש"],next60:["לחזק הוכחות להצעה","לבדוק תגובת הקהל"]},
 MESSAGE:{headline:"המסר לא מחבר מספיק בין הבעיה לפתרון",diagnosis:"יש פעילות שיווקית, אבל הקהל לא תמיד מבין במהירות למה ההצעה רלוונטית דווקא לו.",impact:"תוכן מפוזר מייצר נראות בלי לבנות משמעות מצטברת. כשהמסר אינו עקבי, העניין נשאר חלש וקשה להוביל לפעולה.",focus:"לבחור מסר מרכזי אחד ולחבר אליו כל תוכן ונקודת מפגש.",avoid:["לא לפרסם רק כדי להיות נוכחת","לא להחליף מסר בכל פוסט","לא להגדיל את כמות התוכן"],steps:[{title:"מזהות",body:"בודקות איזה מסר חוזר ואיזה נעלם.",task:"סמני את המסר בכל אחד מחמשת התכנים האחרונים"},{title:"מנסחות",body:"בונות משפט שמחבר קהל, בעיה והצעה.",task:"כתבי משפט מסר מרכזי אחד"},{title:"מחברות",body:"מתכננות תוכן שמחזק אותו מזוויות שונות.",task:"בחרי שלושה נושאים שמובילים לאותה הצעה"}],today:"עברִי על חמשת התכנים האחרונים וסמני אילו מהם מובילים בבירור להצעה המרכזית.",first30:["שבוע 1: בדיקת המסרים הקיימים","שבוע 2: ניסוח מסר מרכזי","שבוע 3: בניית רצף תוכן","שבוע 4: בדיקת עניין ותגובה"],next60:["לחזק הוכחות וסיפורים","לשפר מסרים לפי תגובות"]},
 REACH:{headline:"המנגנון להבאת קהל חדש אינו יציב",diagnosis:"הבסיס השיווקי נראה מספיק ברור, אבל אין כרגע דרך עקבית להביא אליו קהל חדש ורלוונטי.",impact:"בלי מנגנון חשיפה קבוע, גם שיווק טוב תלוי בהמלצות ובהזדמנויות מזדמנות. הצמיחה נעשית קשה לחיזוי.",focus:"לבחור ערוץ חשיפה אחד שאפשר להפעיל בקביעות ולמדוד פניות מתאימות.",avoid:["לא להתפזר בין פלטפורמות","לא לרדוף אחרי כל טרנד","לא לשנות מסר שעובד"],steps:[{title:"בודקות",body:"מזהות מאיפה הגיעו הלקוחות הטובים.",task:"רשמי את מקור עשר הפניות האחרונות"},{title:"בוחרות",body:"מחליטות על ערוץ אחד שמתאים לקהל ולקיבולת.",task:"בחרי ערוץ מרכזי ל־30 יום"},{title:"מתמידות",body:"בונות שגרת חשיפה פשוטה.",task:"קבעי שתי פעולות חשיפה שבועיות"}],today:"רשמי מאיפה הגיעו עשר הפניות האחרונות וסמני את המקור האיכותי ביותר.",first30:["שבוע 1: מיפוי מקורות פנייה","שבוע 2: בחירת ערוץ מרכזי","שבוע 3: יצירת שגרת חשיפה","שבוע 4: מדידת פניות מתאימות"],next60:["לשפר את הערוץ הנבחר","להוסיף ערוץ רק אחרי יציבות"]},
 CONVERSION:{headline:"העניין לא הופך למסלול פעולה ברור",diagnosis:"כבר יש עניין או פניות, אבל הדרך לצעד הבא והטיפול שאחריו אינם עובדים ברצף מספיק ברור.",impact:"כל חיכוך בין עניין לפעולה גורם להזדמנויות להיעלם. לפני שמביאים עוד קהל, כדאי לוודא שהדרך לפנייה והמעקב אחריה פשוטים ועקביים.",focus:"לבנות צעד הבא אחד ברור ותהליך קבוע לטיפול בכל פנייה.",avoid:["לא להזרים עוד תנועה למסלול דולף","לא להוסיף כמה הנעות לפעולה","לא להשאיר מעקב לזיכרון"],steps:[{title:"עוברות במסלול",body:"בודקות כל נקודה מתוכן ועד טיפול בפנייה.",task:"בצעי בעצמך את מסלול הפנייה המלא"},{title:"מפשטות",body:"בוחרות פעולה אחת וכלל טיפול אחד.",task:"קבעי הנעה אחת וזמן חזרה קבוע"},{title:"סוגרות מעקב",body:"מתעדות כל פנייה ומה קרה איתה.",task:"פתחי טבלת מעקב פשוטה"}],today:"בצעי בעצמך את כל הדרך מתוכן אחד ועד שליחת פנייה ורשמי היכן יש חיכוך.",first30:["שבוע 1: מיפוי מסלול הפנייה","שבוע 2: פישוט ההנעה לפעולה","שבוע 3: בניית טיפול ומעקב","שבוע 4: בדיקת אובדן פניות"],next60:["לשפר את נקודת החיכוך העיקרית","למדוד מעבר בין שלבים"]},
 CAPACITY:{headline:"תכנית השיווק גדולה מהקיבולת הזמינה",diagnosis:"ברור יחסית מה צריך לעשות, אבל היקף העבודה הנוכחי אינו בר קיימא בזמן ובאנרגיה שיש לעסק.",impact:"תכנית שאי אפשר להחזיק יוצרת התחלות, עצירות ותחושת כישלון. כאן הפתרון אינו עוד מוטיבציה, אלא מערכת קטנה יותר.",focus:"לצמצם את השיווק למינימום האפקטיבי שאפשר לבצע גם בשבוע רגיל.",avoid:["לא להוסיף פלטפורמה","לא להעלות תדירות","לא לבנות שגרה לשבוע מושלם"],steps:[{title:"ממפות עומס",body:"מזהות מה נופל ומה גוזל זמן.",task:"רשמי את כל משימות השיווק השבועיות"},{title:"מצמצמות",body:"שומרות רק את הפעולות הקריטיות.",task:"בחרי עד שלוש פעולות קבועות"},{title:"מקבעות",body:"יוצרות קצב שאפשר להחזיק.",task:"שבצי זמן קבוע אחד לשיווק"}],today:"רשמי את כל פעולות השיווק השבועיות ומחקי אחת שאינה משרתת ישירות את המטרה.",first30:["שבוע 1: מיפוי עומס","שבוע 2: צמצום משימות","שבוע 3: בניית שגרה אפשרית","שבוע 4: בדיקת התמדה"],next60:["לאוטומט משימה חוזרת","להרחיב רק אם השגרה יציבה"]},
 MEASUREMENT:{headline:"חסרה תמונה אמינה של מה באמת עובד",diagnosis:"יש עשייה, אבל בלי מעקב פשוט קשה לדעת מה מביא פניות טובות ומה רק צורך זמן.",impact:"ללא מדידה בסיסית, החלטות מתקבלות לפי תחושה. קשה לחזק פעולות טובות, לעצור בזבוז וללמוד מהמסלול של כל פנייה.",focus:"לבנות מעקב קטן שמחבר מקור פנייה, סיבה לפנייה, התאמה ותוצאה.",avoid:["לא לבנות דשבורד מורכב","לא למדוד מדדי נראות בלבד","לא לשנות הכול לפני שנאסף בסיס נתונים"],steps:[{title:"מגדירות",body:"בוחרות את ארבעת הנתונים שבאמת עוזרים להחליט.",task:"בחרי מקור, סיבה, התאמה ותוצאה"},{title:"אוספות",body:"מתעדות כל פנייה באותו מקום.",task:"פתחי טבלה והכניסי את הפניות האחרונות"},{title:"לומדות",body:"בודקות דפוס אחד בכל שבוע.",task:"קבעי בדיקה שבועית של 15 דקות"}],today:"פתחי טבלה עם ארבע עמודות: מקור הפנייה, מה גרם לפנייה, התאמה ומה קרה בסוף.",first30:["שבוע 1: הגדרת נתוני המינימום","שבוע 2: איסוף עקבי","שבוע 3: זיהוי דפוסים","שבוע 4: החלטה על שינוי אחד"],next60:["לחזק מקור איכותי","להפסיק פעולה שאינה תורמת"]}
};

const questionMap=()=>new Map([...CORE_QUESTIONS,...Object.values(DECISION_QUESTIONS)].map(q=>[q.id,q]));
function collect(answers:AnswerRecord[]){const scores=Object.fromEntries(DIAGNOSTIC_AREAS.map(a=>[a,0])) as Record<DiagnosticArea,number>;const support=Object.fromEntries(DIAGNOSTIC_AREAS.map(a=>[a,[]])) as Record<DiagnosticArea,EvidenceItem[]>;const contra=Object.fromEntries(DIAGNOSTIC_AREAS.map(a=>[a,[]])) as Record<DiagnosticArea,EvidenceItem[]>;const excluded=new Map<DiagnosticArea,string>();const facts=new Set<string>();let unknown=0;for(const a of answers){const q=questionMap().get(a.questionId),x=q?.options.find(v=>v.id===a.optionId);if(!q||!x)continue;if(x.unknown)unknown++;x.facts?.forEach(f=>facts.add(f));Object.entries(x.scores||{}).forEach(([k,v])=>scores[k as DiagnosticArea]+=v||0);x.supports?.forEach(k=>support[k].push({area:k,text:x.evidence||x.label}));x.contradicts?.forEach(k=>contra[k].push({area:k,text:x.evidence||x.label}));x.excludes?.forEach(k=>excluded.set(k,x.evidence||"נאספה עדות ישירה שהתחום מתפקד"))}return{scores,support,contra,excluded,facts,unknown}}
export function createCandidateSet(answers:AnswerRecord[]){const c=collect(answers);return DIAGNOSTIC_AREAS.slice().filter(a=>!c.excluded.has(a)&&c.scores[a]>=8).sort((a,b)=>c.scores[b]-c.scores[a]).slice(0,3)}
export function buildQuestionPath(answers:AnswerRecord[]):Question[]{if(answers.filter(a=>CORE_QUESTIONS.some(q=>q.id===a.questionId)).length<8)return[];const c=createCandidateSet(answers),out:Question[]=[];for(let i=0;i<c.length;i++)for(let j=i+1;j<c.length;j++){const q=DECISION_QUESTIONS[[c[i],c[j]].sort().join("|")];if(q&&!out.some(x=>x.id===q.id))out.push(q)}return out.slice(0,2)}
function choose(c:ReturnType<typeof collect>){let valid=DIAGNOSTIC_AREAS.filter(a=>!c.excluded.has(a));const upstream:DiagnosticArea[]=["DIRECTION","AUDIENCE","OFFER","MESSAGE","CONVERSION","REACH"];
 if(c.facts.has("leads_exist"))c.excluded.set("REACH","כבר מגיעות פניות. הבעיה נמצאת בהתאמה או במסלול שאחריהן");
 if(upstream.slice(0,5).some(a=>c.scores[a]>=18&&!c.excluded.has(a)))c.excluded.set("REACH","אחד השלבים שקודמים לחשיפה עדיין דורש טיפול");
 valid=valid.filter(a=>!c.excluded.has(a)).sort((a,b)=>c.scores[b]-c.scores[a]);
 if(c.facts.has("execution_unclear")&&c.scores.DIRECTION>=18)valid=["DIRECTION",...valid.filter(a=>a!=="DIRECTION")];
 else if(c.facts.has("execution_clear")&&c.scores.CAPACITY>=22)valid=["CAPACITY",...valid.filter(a=>a!=="CAPACITY")];
 else {const top=valid[0];const causal=upstream.find(a=>valid.includes(a)&&c.scores[top]-c.scores[a]<=5&&c.support[a].length>=1);if(causal)valid=[causal,...valid.filter(a=>a!==causal)]}
 return valid;
}
export function evaluateDiagnostic(answers:AnswerRecord[]):DiagnosticResult {const c=collect(answers),ordered=choose(c),primary=ordered[0],runner=ordered[1],gap=primary&&runner?c.scores[primary]-c.scores[runner]:0;const coreCount=answers.filter(a=>CORE_QUESTIONS.some(q=>q.id===a.questionId)).length;const unresolved=Math.abs(gap)<=3&&!!runner;const confidence:Confidence=coreCount<8||c.unknown>=2||!primary||c.scores[primary]<10||!c.support[primary].length||unresolved?"INSUFFICIENT":c.support[primary].length>=2&&c.contra[primary].length===0&&gap>=8?"HIGH":"MEDIUM";const chosen=confidence==="INSUFFICIENT"?null:primary;const secondary=chosen&&runner&&c.scores[runner]>=15&&gap<=15?runner:null;const base=chosen?COPY[chosen]:null;const evidence=chosen?[...c.support[chosen],...answers.flatMap(a=>{const q=questionMap().get(a.questionId),x=q?.options.find(v=>v.id===a.optionId);return x?.evidence&&x.supports?.some(s=>s===chosen)?[{area:chosen,text:x.evidence}]:[]})].filter((v,i,x)=>x.findIndex(y=>y.text===v.text)===i).slice(0,3):[];return {mode:"PUBLIC",primary:chosen,secondary,confidence,headline:base?.headline||"עוד מוקדם לקבוע מה באמת מעכב את השיווק שלך",oneLineDiagnosis:base?.diagnosis||"התשובות עדיין אינן יוצרות תמונה עקבית מספיק. קודם נאסוף מינימום מידע ונבדוק שוב.",evidence,contradictions:chosen?c.contra[chosen].slice(0,3):[],impact:base?.impact||"בלי נתונים בסיסיים על מקור הפניות, התאמתן ומה קרה בסוף, כל מסקנה תהיה מוקדמת מדי.",focusNow:base?.focus||"לאסוף במשך 14 יום מידע בסיסי על כל פנייה.",avoidNow:base?.avoid||["לא לשנות אסטרטגיה לפי תחושה","לא להגדיל תקציב לפני איסוף מידע","לא להסיק מסקנה מפנייה בודדת"],actionMap:base?.steps||[{title:"מתעדות",body:"אוספות מידע בסיסי על כל פנייה.",task:"פתחי טבלה פשוטה"},{title:"בודקות",body:"מחפשות דפוס שחוזר בנתונים.",task:"בדקי את הנתונים פעם בשבוע"},{title:"מחליטות",body:"בוחרות שינוי קטן אחד לבדיקה.",task:"שני רק משתנה אחד"}],firstActionToday:base?.today||"פתחי טבלה עם מקור הפנייה, מה גרם לפנייה, התאמה ומה קרה בסוף.",secondaryNote:secondary?`יש גם סימנים לפער בתחום ${AREA_LABELS[secondary]}, אבל נכון לטפל קודם ב${AREA_LABELS[chosen!]}.`:undefined,recommendedStartingPoint:(base?.first30||[]).slice(0,3),strategySeed:{positioning:chosen==="DIRECTION",audience:chosen==="AUDIENCE",offer:chosen==="OFFER",message:chosen==="MESSAGE",channels:chosen==="REACH",conversion:chosen==="CONVERSION",capacity:chosen==="CAPACITY",measurement:chosen==="MEASUREMENT"},workPlanSeed:{first30:base?.first30||["שבוע 1: פתיחת מעקב","שבוע 2: איסוף עקבי","שבוע 3: זיהוי דפוסים","שבוע 4: בחירת ניסוי קטן"],next60:base?.next60||["להמשיך למדוד","לחזק רק מה שנמצא יעיל"],postpone:base?.avoid||["שינויים רחבים"]},questionsAsked:answers.map(a=>a.questionId),answers,candidates:createCandidateSet(answers),excluded:[...c.excluded].map(([area,reason])=>({area,reason})),scores:c.scores};}
export function buildClientStartingPoint(result:DiagnosticResult):ClientStartingPoint {const label=result.primary?AREA_LABELS[result.primary]:"איסוף מידע";return{diagnosisSummary:result.oneLineDiagnosis,questionsToValidateInMeeting:[`מה כבר ניסית בתחום ${label}?`,`איזו תוצאה תיחשב שינוי משמעותי?`,`מה עלול להקשות על היישום?`],recommendedWorkOrder:[result.focusNow,...result.actionMap.map(s=>s.title)],first30Days:result.workPlanSeed.first30,next60Days:result.workPlanSeed.next60,inputsNeededFromClient:["מקורות הפנייה האחרונים","דוגמאות לתוכן ולהצעה","תהליך הטיפול בפניות"],strategySectionsToBuild:Object.entries(result.strategySeed).filter(([,v])=>v).map(([k])=>k)};}
