export const DIAGNOSTIC_AREAS=["goal","focus","audience","response","message","reach","consistency"] as const;
export type DiagnosticArea=(typeof DIAGNOSTIC_AREAS)[number];
export type HealthState="healthy"|"needs_attention"|"critical"|"unknown";
export type Confidence="HIGH"|"MEDIUM"|"INSUFFICIENT";
export type AnswerRecord={questionId:string;optionId:string};
export type Option={id:string;label:string;state:HealthState;evidence?:string;unknown?:boolean};
export type Question={id:DiagnosticArea;stage:string;title:string;options:Option[]};
export type ResultStep={label:string;title:string;body:string};
export type DiagnosticResult={primary:DiagnosticArea|null;confidence:Confidence;states:Record<DiagnosticArea,HealthState>;headline:string;summary:string;whatWorks:string;bottleneck:string;priority:string;cause:string;evidence:string[];steps:ResultStep[];plan:string[];avoid:string[];firstAction:string;visual:DiagnosticArea;answers:AnswerRecord[]};
export const AREA_LABELS:Record<DiagnosticArea,string>={goal:"מטרה",focus:"מיקוד",audience:"קהל",response:"תגובה לשיווק",message:"מסר",reach:"קהל חדש",consistency:"התמדה"};
const o=(id:string,label:string,state:HealthState,evidence?:string):Option=>({id,label,state,evidence,unknown:state==="unknown"});
export const CORE_QUESTIONS:Question[]=[
 {id:"goal",stage:"מטרה",title:"מה הכי היית רוצה שיקרה בשיווק שלך בחודשיים הקרובים?",options:[o("recognition","יותר אנשים נכונים יכירו את העסק","healthy","בחרת להגדיל היכרות עם העסק"),o("more_leads","יותר מתעניינים יהפכו לפניות","healthy","המטרה שלך היא לייצר יותר פניות"),o("more_clients","יותר פניות יהפכו ללקוחות","healthy","המטרה שלך היא לשפר את המעבר מפנייה ללקוחה"),o("order","לעשות סדר במה לשווק ואיך","needs_attention","הצורך המרכזי שסימנת הוא ליצור סדר בשיווק"),o("sustain","להצליח להתמיד בלי עומס","needs_attention","המטרה שסימנת היא לבנות שיווק שאפשר להחזיק") ]},
 {id:"focus",stage:"מיקוד",title:"עד כמה ברור לך מה את רוצה לקדם עכשיו?",options:[o("clear","מאוד ברור. יש לי הצעה מרכזית","healthy","יש לך הצעה מרכזית שברור לך לקדם"),o("several","יש כמה דברים ואני מתלבטת","needs_attention","כמה דברים מתחרים כרגע על תשומת הלב שלך"),o("changes","אני משנה את המיקוד לעיתים קרובות","critical","המיקוד השיווקי משתנה לעיתים קרובות"),o("unsure","אני לא בטוחה מה נכון לקדם","critical","לא ברור כרגע מה נכון לקדם") ]},
 {id:"audience",stage:"קהל",title:"עד כמה ברור לך מי הלקוחה שהכי מתאימה להצעה הזאת?",options:[o("clear","ברור לי מאוד","healthy","ברור לך מי הלקוחה המתאימה להצעה"),o("broad","יש לי כיוון, אבל הקהל רחב","needs_attention","הקהל שאת פונה אליו עדיין רחב"),o("unsuitable","מגיעות אליי פניות לא מספיק מתאימות","critical","מגיעות פניות, אבל רבות מהן אינן מתאימות"),o("unknown","אני עדיין לא יודעת מספיק טוב למי לפנות","unknown","עדיין אין מספיק בהירות לגבי הקהל") ]},
 {id:"response",stage:"תגובה לשיווק",title:"כשאנשים נחשפים לשיווק שלך, מה קורה בדרך כלל?",options:[o("good","יש עניין וגם מגיעות פניות מתאימות","healthy","החשיפה מייצרת עניין ופניות מתאימות"),o("interest_low_action","יש עניין, אבל מעט פניות","critical","נוצר עניין, אבל הוא כמעט לא הופך לפניות"),o("bad_leads","מגיעות פניות, אבל רבות מהן לא מתאימות","critical","נכנסות פניות, אך ההתאמה שלהן נמוכה"),o("postlead","מגיעות פניות, אבל מעט מהן נסגרות","critical","פניות נכנסות, אבל מעט מהן הופכות ללקוחות"),o("no_response","כמעט שאין תגובה","critical","החשיפה כמעט אינה מייצרת תגובה"),o("unknown","אני לא באמת יודעת","unknown","אין כרגע תמונה ברורה של תגובת הקהל") ]},
 {id:"message",stage:"מסר",title:"עד כמה ברור מהשיווק שלך מה את מציעה ולמי זה מתאים?",options:[o("clear","ברור מאוד","healthy","המסר והחיבור להצעה ברורים"),o("mostly","די ברור, אבל לא תמיד","needs_attention","המסר ברור רק בחלק מנקודות המפגש"),o("disconnected","יש תוכן טוב, אבל הוא לא מספיק מחובר להצעה","critical","התוכן אינו מחובר מספיק להצעה"),o("scattered","התוכן מפוזר בין יותר מדי נושאים","critical","התוכן מפוזר בין נושאים ומסרים רבים"),o("unknown","אני לא בטוחה","unknown","קשה כרגע להעריך עד כמה המסר ברור") ]},
 {id:"reach",stage:"קהל חדש",title:"איך מגיעים אלייך היום לקוחות חדשים?",options:[o("steady","יש לי ערוץ אחד או יותר שעובדים באופן קבוע","healthy","יש ערוץ קבוע שמביא לקוחות חדשים"),o("referrals","בעיקר דרך המלצות","needs_attention","רוב הלקוחות החדשים מגיעים מהמלצות"),o("content_unstable","דרך תוכן, אבל בלי יציבות","needs_attention","התוכן מביא קהל חדש, אך לא ביציבות"),o("occasional","דרך קמפיינים או שיתופי פעולה מדי פעם","needs_attention","החשיפה החדשה נשענת על פעולות מזדמנות"),o("none","כמעט שאין לי דרך קבועה להגיע לקהל חדש","critical","אין דרך קבועה להגיע לקהל חדש"),o("unknown","אני לא באמת יודעת","unknown","לא ידוע כרגע מאיפה מגיעים לקוחות חדשים") ]},
 {id:"consistency",stage:"התמדה",title:"מה הכי מקשה עלייך להחזיק את השיווק לאורך זמן?",options:[o("dont_know","אני לא תמיד יודעת מה נכון לעשות","critical","חוסר הבהירות לגבי מה נכון לעשות מקשה על הביצוע"),o("what_post","קשה לי לדעת מה לפרסם","needs_attention","הקושי לבחור מה לפרסם פוגע ברצף"),o("too_much","אני מנסה לעשות יותר מדי דברים","critical","ניסיון לעשות יותר מדי מקשה על ההתמדה"),o("no_time","אין לי מספיק זמן","critical","אין מספיק זמן להחזיק את השיווק הנוכחי"),o("cant_sustain","אני מתחילה ולא מצליחה להתמיד","critical","קשה לשמור על רצף לאורך זמן"),o("consistent","אני עקבית, אבל התוצאות לא מספיק טובות","healthy","השיווק מתבצע בעקביות, גם אם התוצאות עדיין חלשות") ]}
];
const COPY:Record<DiagnosticArea,{headline:string;summary:string;works:string;bottleneck:string;priority:string;cause:string;steps:[string,string,string];plan:string[];avoid:string[];first:string}>={
 goal:{headline:"יש עשייה שיווקית, אבל עדיין אין יעד אחד שמארגן אותה",summary:"התשובות שלך מצביעות על צורך בסדר לפני הרחבה. בלי יעד ברור קשה להחליט איזה מהלך ראוי לקבל זמן ותקציב.",works:"יש רצון להתקדם ונכונות להשקיע בשיווק.",bottleneck:"המטרה עדיין אינה מתורגמת לתוצאה עסקית אחת שאפשר לכוון אליה.",priority:"קודם מגדירות תוצאה, אחר כך בוחרות מה לקדם ורק אז מתכננות תוכן וחשיפה.",cause:"כאשר אין יעד אחד, גם החלטות טובות נשארות מנותקות זו מזו.",steps:["להגדיר תוצאה עסקית אחת לחודשיים","לבחור הצעה אחת שמשרתת אותה","לחבר אליה תוכן וערוץ חשיפה"],plan:["להגדיר יעד ותנאי הצלחה","לבחור הצעה מרכזית","לנסח מסר שמוביל ליעד","לבנות שגרת פעולה ומדידה"],avoid:["לא לפתוח ערוץ חדש","לא לקדם כמה מטרות במקביל","לא למדוד הצלחה רק לפי פעילות"],first:"כתבי במשפט אחד איזו תוצאה עסקית השיווק צריך לייצר בתוך חודשיים."},
 focus:{headline:"יש לך פעילות שיווקית, אבל כרגע אין החלטה אחת שמארגנת אותה",summary:"הבעיה לא מתחילה בתוכן. כמה הצעות או כיוונים מתחרים על תשומת הלב, ולכן גם המסר והביצוע מתפזרים.",works:"יש לך רעיונות והצעות שאפשר לעבוד איתם.",bottleneck:"אין כרגע בחירה אחת שמגדירה מה מקדמים ולמה דווקא עכשיו.",priority:"קודם בוחרות מוקד אחד. רק אחר כך מחדדות מסר ומגדילות פעילות.",cause:"ריבוי אפשרויות מייצר עומס ומונע הצטברות של מסר ברור לאורך זמן.",steps:["לבחור הצעה אחת לתקופה הקרובה","להסיר פעולות שאינן משרתות אותה","לבנות רצף מסרים וחשיפה"],plan:["למפות את כל מה שמקודם","לבחור מוקד אחד","לחבר אליו את המסר","לבנות תכנית שבועית מצומצמת"],avoid:["לא להוסיף עוד הצעה","לא להגדיל תדירות","לא לבנות קמפיין לפני הבחירה"],first:"רשמי את כל מה שאת מנסה לקדם וסמני הצעה אחת שתוביל את 60 הימים הקרובים."},
 audience:{headline:"את יודעת מה את רוצה לקדם, אבל עדיין לא מספיק ברור למי זה הכי מתאים",summary:"גם הצעה טובה ומסר ברור מתקשים לעבוד כשהם מגיעים לקהל רחב או לא מדויק.",works:"יש כיוון שיווקי שאפשר לתרגם להצעה ממוקדת.",bottleneck:"הגדרת הקהל אינה מסננת מספיק בין מי שמתעניינת לבין מי שבאמת מתאימה.",priority:"קודם מחדדות את הלקוחה הנכונה, אחר כך מתאימות מסר ורק אז מגדילות חשיפה.",cause:"כשמנסים לדבר לכולן, המסר מאבד רלוונטיות ומגיעות יותר פניות לא מתאימות.",steps:["לנתח שלוש לקוחות טובות","להגדיר סימני התאמה וצורך","לעדכן מסר וערוצי חשיפה"],plan:["למפות לקוחות ופניות","לנסח פרופיל קהל מדויק","להתאים הצעה ומסר","לבדוק את איכות הפניות"],avoid:["לא להגדיל חשיפה לקהל רחב","לא לדבר לכולן","לא לשנות את כל ההצעה"],first:"בחרי שלוש לקוחות טובות וכתבי מה היה משותף להן ברגע שבו פנו."},
 response:{headline:"את מצליחה להביא אנשים לראות אותך, אבל משהו בין החשיפה לפנייה לא מספיק עובד",summary:"נוצר עניין או נכנסות פניות, אבל המעבר לשלב הבא אינו רציף מספיק. כאן צריך לבדוק את הדרך מהתגובה לפעולה.",works:"הקהל כבר פוגש את השיווק ויש סימנים של עניין.",bottleneck:"העניין אינו הופך באופן עקבי לפנייה מתאימה או ללקוחה.",priority:"קודם מתקנות את נקודת הנפילה במסלול, ורק אחר כך מביאות עוד קהל.",cause:"הנעה לא ברורה, חיכוך בדרך או מעקב לא עקבי גורמים להזדמנויות להיעלם.",steps:["למפות את הדרך מחשיפה ללקוחה","לתקן את נקודת הנפילה המרכזית","להגדיל תנועה רק אחרי בדיקה"],plan:["למפות את ארבעת שלבי המסלול","לבדוק הנעה ונקודת פנייה","לסדר טיפול ומעקב","למדוד מעבר בין השלבים"],avoid:["לא להגדיל תקציב חשיפה","לא להוסיף כמה הנעות לפעולה","לא להשאיר פניות ללא מעקב"],first:"עברִי בעצמך על הדרך מתוכן אחד ועד לפנייה ורשמי היכן הצעד הבא אינו ברור."},
 message:{headline:"הקהל פוגש אותך, אבל המסר עדיין לא בונה הבנה אחת ברורה",summary:"יש נוכחות ותוכן, אך הם אינם מצטברים לסיפור עקבי שמחבר בין הבעיה, ההצעה והצעד הבא.",works:"יש לך פעילות ונקודות מפגש עם הקהל.",bottleneck:"התוכן מפוזר או מנותק מההצעה שאת רוצה לקדם.",priority:"קודם מנסחות מסר מרכזי, אחר כך בונות סביבו תוכן ורק אז מרחיבות הפצה.",cause:"כל מסר חדש מתחיל מחדש במקום לחזק הבנה שכבר נבנתה.",steps:["לנסח מסר מרכזי אחד","לחבר אליו שלושה נושאי תוכן","לבנות רצף שמוביל להצעה"],plan:["לבדוק את התוכן הקיים","לנסח מסר מרכזי","לבנות רצף תכנים","לבדוק עניין ותגובה"],avoid:["לא לפרסם רק כדי להיות נוכחת","לא להחליף מסר בכל פוסט","לא להגדיל כמות לפני חידוד"],first:"עברִי על חמשת התכנים האחרונים וסמני אילו מהם מובילים בבירור לאותה הצעה."},
 reach:{headline:"הבסיס שלך יחסית מסודר. מה שחסר עכשיו הוא כניסה קבועה של אנשים חדשים",summary:"הבעיה אינה במה שאת אומרת, אלא בכמה אנשים רלוונטיים נחשפים לזה באופן עקבי.",works:"המיקוד, הקהל והמסר נראים ברורים יחסית.",bottleneck:"אין מנגנון קבוע שמביא קהל חדש מעבר להזדמנויות והמלצות.",priority:"שומרות על הבסיס הקיים ובונות ערוץ חשיפה אחד שאפשר להפעיל לאורך זמן.",cause:"חשיפה מזדמנת מקשה לייצר קצב פניות שאפשר לחזות ולשפר.",steps:["למפות מאיפה הגיעו לקוחות טובים","לבחור ערוץ חשיפה אחד","לבנות שגרה ולמדוד פניות"],plan:["למפות מקורות פנייה","לבחור ערוץ מרכזי","להפעיל שגרת חשיפה","לבדוק איכות וקצב פניות"],avoid:["לא לבנות מחדש את המיתוג","לא להתפזר בין ערוצים","לא לשנות מסר שעובד"],first:"רשמי מאיפה הגיעו עשר הפניות האחרונות וסמני את המקור האיכותי ביותר."},
 consistency:{headline:"הכיוון שלך לא בהכרח הבעיה. המערכת פשוט קשה מדי להחזקה לאורך זמן",summary:"ברור יחסית מה צריך לעשות, אבל היקף הפעולות אינו מתאים לזמן ולאנרגיה שיש בפועל.",works:"יש בסיס שיווקי והבנה של הפעולות הנדרשות.",bottleneck:"שגרת השיווק הנוכחית גדולה מדי ולכן היא נשברת שוב ושוב.",priority:"קודם מצמצמות את המערכת לקצב אפשרי. הרחבה מגיעה רק אחרי שנוצרת יציבות.",cause:"תכנית שנבנתה לשבוע מושלם אינה מחזיקה בתוך העבודה השוטפת של העסק.",steps:["למפות את עומס השיווק","לבחור עד שלוש פעולות קבועות","להרחיב רק אחרי חודש יציב"],plan:["למפות עומס ונקודות נפילה","לצמצם פעולות","לבנות לוח שבועי אפשרי","לבדוק התמדה ולהתאים"],avoid:["לא להוסיף פלטפורמה","לא להעלות תדירות","לא לבנות שגרה לשבוע מושלם"],first:"רשמי את כל פעולות השיווק השבועיות ומחקי אחת שאינה משרתת ישירות את המטרה."}
};
function answered(answers:AnswerRecord[]){const map=new Map(answers.map(a=>[a.questionId,a.optionId]));return Object.fromEntries(CORE_QUESTIONS.map(q=>{const x=q.options.find(o=>o.id===map.get(q.id));return[q.id,x]})) as Record<DiagnosticArea,Option|undefined>}
export function evaluateDiagnostic(answers:AnswerRecord[]):DiagnosticResult{const x=answered(answers),states=Object.fromEntries(DIAGNOSTIC_AREAS.map(a=>[a,x[a]?.state||"unknown"])) as Record<DiagnosticArea,HealthState>;const bad=(a:DiagnosticArea)=>states[a]==="critical"||states[a]==="needs_attention",is=(a:DiagnosticArea,id:string)=>x[a]?.id===id;let primary:DiagnosticArea|null=null;
 if(answers.length<7||DIAGNOSTIC_AREAS.filter(a=>states[a]==="unknown").length>=3)primary=null;
 else if(bad("focus")&&(is("goal","order")||is("consistency","dont_know")||states.focus==="critical"))primary="focus";
 else if(bad("audience")||is("response","bad_leads"))primary="audience";
 else if(bad("message")&&(is("response","no_response")||states.reach==="healthy"))primary="message";
 else if(bad("response")&&(states.reach==="healthy"||is("response","interest_low_action")||is("response","postlead")))primary="response";
 else if(bad("consistency")&&states.focus==="healthy")primary="consistency";
 else if(bad("reach")&&states.focus==="healthy"&&states.audience==="healthy"&&states.message==="healthy")primary="reach";
 else if(bad("focus"))primary="focus";else if(bad("message"))primary="message";else if(bad("response"))primary="response";else if(bad("reach"))primary="reach";else if(bad("consistency"))primary="consistency";else if(bad("goal"))primary="goal";
 const confidence:Confidence=!primary?"INSUFFICIENT":states[primary]==="critical"?"HIGH":"MEDIUM",base=primary?COPY[primary]:COPY.goal;const evidence=DIAGNOSTIC_AREAS.map(a=>x[a]?.evidence).filter(Boolean) as string[];const relevant=primary?[x[primary]?.evidence,...DIAGNOSTIC_AREAS.filter(a=>a!==primary&&bad(a)).map(a=>x[a]?.evidence)].flat().filter(Boolean).slice(0,3) as string[]:evidence.slice(0,3);return{primary,confidence,states,headline:primary?base.headline:"עדיין אין מספיק מידע כדי לקבוע מה באמת מעכב את השיווק שלך",summary:primary?base.summary:"חלק מהתשובות עדיין אינן יוצרות תמונה עקבית. איסוף קצר של נתוני פניות יעזור לקבל החלטה טובה יותר.",whatWorks:primary?base.works:"עצם המיפוי כבר מראה אילו נתונים חסרים.",bottleneck:primary?base.bottleneck:"חסרה תמונה עקבית של מה קורה בין החשיפה לפנייה וללקוחה.",priority:primary?base.priority:"קודם אוספות מידע בסיסי במשך 14 יום ורק אחר כך משנות את השיווק.",cause:primary?base.cause:"בלי נתונים, קשה להפריד בין תחושה לבין דפוס שחוזר.",evidence:relevant,steps:[{label:"עכשיו",title:base.steps[0],body:"זה הצעד שמטפל בשורש לפני שמוסיפים עוד פעילות."},{label:"אחרי שזה מסודר",title:base.steps[1],body:"רק לאחר שהבסיס ברור, מחברות אליו את השלב הבא."},{label:"רק אחר כך",title:base.steps[2],body:"מרחיבות באופן מדוד בלי לאבד את המיקוד."}],plan:base.plan,avoid:base.avoid,firstAction:base.first,visual:primary||"goal",answers};}
