"use client";
/* eslint-disable @next/next/no-img-element */
import {useMemo,useState} from "react";
import {AREA_LABELS,CORE_QUESTIONS,DIAGNOSTIC_AREAS,buildQuestionPath,evaluateDiagnostic,type AnswerRecord,type DiagnosticArea,type DiagnosticResult,type Question} from "./diagnostic-engine";
const certainty={HIGH:"גבוהה",MEDIUM:"בינונית",INSUFFICIENT:"אין עדיין מספיק מידע"};
const icons:Record<DiagnosticArea,string>={DIRECTION:"⌖",AUDIENCE:"◎",OFFER:"◇",MESSAGE:"≋",REACH:"↗",CONVERSION:"⇢",CAPACITY:"▤",MEASUREMENT:"⌁"};
function Mark(){return <img className="tr-mark" src="/tali-mark.png" alt="סמל TR של טלי רוזנברג"/>}
function AreaMap({result,preview=false}:{result?:DiagnosticResult;preview?:boolean}){return <div className="area-map" role="img" aria-label={preview?"מפה של שמונת תחומי השיווק":"מפת האבחון שלך"}><div className="map-core"><small>{preview?"סריקה שיווקית":"השיווק שלך"}</small><strong>{preview?"מה עוצר?":"מיפוי"}</strong></div>{DIAGNOSTIC_AREAS.map((area,i)=>{const state=result?.primary===area?"primary":result?.secondary===area?"secondary":result?.excluded.some(x=>x.area===area)?"healthy":result&&!result.candidates.includes(area)?"healthy":"watch";return <div className={`area-node node-${i+1} ${state}`} key={area}><span>{state==="primary"?"!":state==="secondary"?"2":state==="healthy"?"✓":icons[area]}</span><b>{AREA_LABELS[area]}</b></div>})}<div className="map-path" aria-hidden="true"/></div>}
function ImpactVisual({area}:{area:DiagnosticArea|null}){const labels:Record<DiagnosticArea,string[]>={DIRECTION:["רעיונות רבים","מטרה אחת","תכנית ברורה"],AUDIENCE:["קהל רחב","התאמה","קהל מדויק"],OFFER:["הרבה הסבר","ערך ברור","הצעה ממוקדת"],MESSAGE:["מסרים מפוזרים","מסר מרכזי","עניין"],REACH:["המלצות","ערוץ קבוע","קהל חדש"],CONVERSION:["עניין","פנייה","טיפול"],CAPACITY:["עומס","צמצום","שגרה"],MEASUREMENT:["פעולות","מעקב","החלטה"]};const list=area?labels[area]:["מקור הפנייה","התאמה","תוצאה"];return <div className={`impact-visual visual-${area?.toLowerCase()||"unknown"}`} role="img" aria-label={`המחשה: ${list.join(", ")}`}>{list.map((x,i)=><div key={x}><i>{i+1}</i><span>{x}</span></div>)}</div>}
function Roadmap({weeks}:{weeks:string[]}){return <ol className="roadmap">{weeks.map((week,i)=><li key={week}><b>{i+1}</b><div><small>שבוע {i+1}</small><p>{week.replace(/^שבוע \d+: /,"")}</p></div></li>)}</ol>}
export default function Home(){
 const[started,setStarted]=useState(false),[index,setIndex]=useState(0),[answers,setAnswers]=useState<AnswerRecord[]>([]),[selected,setSelected]=useState<string|null>(null),[todayDone,setTodayDone]=useState(false);
 const core=answers.filter(a=>CORE_QUESTIONS.some(q=>q.id===a.questionId));const dynamic=core.length===8?buildQuestionPath(core):[];const questions:Question[]=[...CORE_QUESTIONS,...dynamic];const done=core.length===8&&index>=questions.length;const result=useMemo(()=>evaluateDiagnostic(answers),[answers]);
 const restart=()=>{setStarted(false);setIndex(0);setAnswers([]);setSelected(null);setTodayDone(false);window.scrollTo({top:0})};
 const choose=(id:string)=>{if(selected)return;setSelected(id);setTimeout(()=>{setAnswers(a=>[...a,{questionId:questions[index].id,optionId:id}]);setIndex(i=>i+1);setSelected(null);window.scrollTo({top:0,behavior:"smooth"})},250)};
 const back=()=>{if(!index){setStarted(false);return}setIndex(i=>i-1);setAnswers(a=>a.slice(0,-1));setSelected(null)};
 return <main dir="rtl"><header className="topbar"><button onClick={restart} aria-label="חזרה להתחלה"><Mark/></button><strong>בדיקת השיווק החכם</strong></header>
 {!started?<><section className="home-hero"><div className="hero-copy"><p className="overline">אבחון אסטרטגי לעסקים קטנים</p><h1>מה באמת תוקע<br/><em>את השיווק שלך עכשיו?</em></h1><p className="lead">לא תמיד צריך עוד פוסט, עוד קמפיין או עוד כלי.<br/>לפעמים צריך לזהות איפה השיווק נתקע.<br/>האבחון הקצר הזה יעזור לך להבין במה נכון להתמקד עכשיו.</p><button className="primary-button" onClick={()=>setStarted(true)}>התחילי את האבחון <span>←</span></button><small className="meta">כ־5 דקות · בלי הרשמה · מפת פעולה אישית בסיום</small></div><div className="hero-map"><AreaMap preview/><p>סורקות שמונה תחומים ומזהות את נקודת החסימה</p></div></section><section className="value-strip"><span>אבחון ממוקד</span><span>שמונה תחומים</span><span>תוצאה אישית</span><span>מפת פעולה ל־30 יום</span></section><section className="how"><header><small>כך זה עובד</small><h2>מסריקה לפעולה, בלי לנחש</h2></header><div>{[["01","סורקות","עוברות על נקודות המפתח בשיווק שלך."],["02","מזהות","מפרידות בין סימפטום לבין צוואר הבקבוק."],["03","מתמקדות","בונות סדר פעולות ברור לחודש הקרוב."]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section><section className="what"><div><small>מה תקבלי בסיום</small><h2>לא עוד רשימת משימות.<br/>מפה שמראה מה קודם.</h2><button className="rose-button" onClick={()=>setStarted(true)}>התחילי עכשיו <span>←</span></button></div><ul><li>צוואר הבקבוק המרכזי</li><li>העדויות שהובילו אליו</li><li>שלושה צעדים ממוקדים</li><li>מפת פעולה ל־30 יום</li></ul></section></>:
 !done?<section className="question-shell" aria-live="polite"><div className="progress-copy"><span>{questions[index]?.stage}</span><b>שאלה {index+1} מתוך {questions.length}</b></div><div className="progress"><i style={{width:`${((index+1)/questions.length)*100}%`}}/></div><article className="question-card"><p className="stage-icon"><span aria-hidden="true">{questions[index].stage==="מטרה"?"⌖":questions[index].stage==="סריקה"?"◎":"◉"}</span>{questions[index].stage}</p><h1>{questions[index].title}</h1><div className="answers">{questions[index].options.map(x=><button key={x.id} className={selected===x.id?"selected":""} disabled={selected!==null} aria-pressed={selected===x.id} onClick={()=>choose(x.id)}><span>{x.label}</span><i>{selected===x.id?"✓":""}</i></button>)}</div></article><button className="back" onClick={back}>← חזרה</button></section>:
 <section className="result-page"><section className="result-hero"><div className="diagnosis"><p>מצאנו את צוואר הבקבוק שלך</p><h1>{result.headline}</h1><span className="confidence">רמת ודאות: <b>{certainty[result.confidence]}</b></span><p>{result.oneLineDiagnosis}</p><small>האבחון מבוסס על {result.evidence.length||answers.length} תשובות שתומכות בכיוון הזה.</small></div><div><h2>מפת האבחון שלך</h2><AreaMap result={result}/><p className="map-caption">כאן נמצאת כרגע נקודת המיקוד המרכזית שלך.</p></div></section>
 <section className="evidence section"><header><span>⌕</span><div><small>העדויות מהתשובות שלך</small><h2>למה הגענו למסקנה הזאת?</h2></div></header><div className="evidence-grid">{(result.evidence.length?result.evidence:[{area:"MEASUREMENT" as DiagnosticArea,text:"עדיין חסר מידע עקבי כדי לבחור הסבר אחד"},{area:"MEASUREMENT" as DiagnosticArea,text:"התשובות מצביעות על יותר מאפשרות אחת"},{area:"MEASUREMENT" as DiagnosticArea,text:"נדרש מעקב קצר לפני החלטה רחבה"}]).slice(0,3).map((e,i)=><article key={e.text}><b>{String(i+1).padStart(2,"0")}</b><small>{AREA_LABELS[e.area]}</small><p>{e.text}</p></article>)}</div></section>
 <section className="impact section"><div><header><span>⌕</span><div><small>המשמעות העסקית</small><h2>מה זה יוצר בפועל?</h2></div></header><p>{result.impact}</p></div><ImpactVisual area={result.primary}/></section><section className="focus section"><small>המיקוד שלך עכשיו</small><h2>{result.focusNow}</h2></section>
 <section className="action section"><header><small>סריקה · זיהוי · מיקוד · פעולה</small><h2>מפת הפעולה שלך</h2></header><ol>{result.actionMap.map((s,i)=><li key={s.title}><b>0{i+1}</b><div><h3>{s.title}</h3><p>{s.body}</p><span>לעשות עכשיו: {s.task}</span></div>{i<2&&<i aria-hidden="true">←</i>}</li>)}</ol></section>
 <section className={`today ${todayDone?"done":""}`}><div><small>הצעד הראשון שלך היום</small><h2>{result.firstActionToday}</h2></div><button onClick={()=>setTodayDone(v=>!v)} aria-pressed={todayDone}>{todayDone?"הצעד הושלם ✓":"סיימתי את הצעד הזה"}</button></section><div className="lower-grid"><section className="avoid"><small>מה כרגע לא צריך</small><h2>שומרות על המיקוד</h2><ul>{result.avoidNow.slice(0,3).map(x=><li key={x}>{x}</li>)}</ul></section>{result.secondaryNote&&<section className="secondary"><small>פער משני</small><h2>{result.secondary&&AREA_LABELS[result.secondary]}</h2><p>{result.secondaryNote}</p></section>}</div>
 <section className="month section"><header><small>30 הימים הקרובים</small><h2>מפת עבודה חודשית</h2></header><Roadmap weeks={result.workPlanSeed.first30}/></section><section className="final-cta"><div><small>השלב הבא</small><h2>רוצה להפוך את המפה הזאת לתכנית שיווק מסודרת?</h2><p>אם זיהית כאן משהו שמוכר לך מהעסק, אפשר לבדוק יחד מה נכון לשנות קודם ואיך לעשות את זה בלי להעמיס עוד שיווק.</p></div><div><a href="https://tali-digicard.vercel.app/" target="_blank" rel="noreferrer">אני רוצה לעשות סדר בשיווק <span>←</span></a><button onClick={restart}>להתחיל אבחון מחדש</button><small>השיחה אינה מחייבת ומתחילה בהיכרות קצרה.</small></div></section></section>}
 <footer><Mark/><span>טלי רוזנברג<br/><small>שיווק דיגיטלי חכם לעסקים קטנים</small></span></footer></main>}
