"use client";
/* eslint-disable @next/next/no-img-element */
import{useMemo,useState}from"react";
import{AREA_LABELS,DIAGNOSTIC_AREAS,evaluateDiagnostic,getQuestionsForAnswers,type AnswerRecord,type DiagnosticArea,type DiagnosticResult}from"./diagnostic-engine";
function Mark(){return <img className="tr-mark" src="/tali-mark.png" alt="סמל TR של טלי רוזנברג"/>}
const visualLabels:Record<DiagnosticArea,string>={goal:"בחירת יעד מרכזי",focus:"התכנסות לבחירה אחת",audience:"זיהוי הקהל המתאים",response:"הדרך מחשיפה ללקוחה",message:"יצירת מסר מרכזי",reach:"חיבור ערוצים לעסק",consistency:"בניית שגרת שיווק"};
function StageVisual({area,compact=false}:{area:DiagnosticArea;compact?:boolean}){return <div className={`stage-visual sv-${area} ${compact?"compact":""}`} role="img" aria-label={visualLabels[area]}>
 {area==="goal"&&<><div className="target"><i/><i/><b>מטרה</b></div><span className="arrow a1">←</span><span className="arrow a2">↙</span><span className="arrow a3">↖</span><small>כיוון אחד שמארגן את השיווק</small></>}
 {area==="focus"&&<><div className="choice-cloud"><i>שירות</i><i>מוצר</i><i>קמפיין</i><i>תוכן</i></div><span className="converge">←</span><b className="one-choice">מוקד אחד</b><small>מה מקדמים עכשיו</small></>}
 {area==="audience"&&<><div className="audience-field">{Array.from({length:18},(_,i)=><i className={i===6||i===7||i===11?"fit":""} key={i}/>)}</div><b className="audience-label">קהל מתאים</b><small>לא כולן הן הקהל שלך</small></>}
 {area==="response"&&<><div className="mini-funnel">{["חשיפה","עניין","פנייה","לקוחה"].map((x,i)=><div key={x} className={i===2?"drop":""}><span>{x}</span>{i<3&&<i>←</i>}</div>)}</div><small>איפה נעצרת התנועה</small></>}
 {area==="message"&&<><div className="message-cloud"><i>רעיון</i><i>טיפ</i><i>סיפור</i></div><span className="converge">←</span><b className="message-core">מסר אחד ברור</b><small>מה הקהל צריך להבין</small></>}
 {area==="reach"&&<><b className="business-hub">העסק</b><div className="channel-list">{["תוכן","המלצות","ממומן","שיתופי פעולה","חיפוש"].map(x=><i key={x}>{x}</i>)}</div><small>מאיפה מגיעים אנשים חדשים</small></>}
 {area==="consistency"&&<><div className="week-grid">{["א","ב","ג","ד","ה"].map((x,i)=><i key={x}><b>{x}</b><span className={i<4?"filled":""}/></i>)}</div><div className="routine-line"><i/><span>התחלה</span><span>שגרה</span><span>התמדה</span></div><small>קצב שאפשר להחזיק</small></>}
 </div>}
function HealthMap({result}:{result:DiagnosticResult}){const stateText={healthy:"עובד יחסית טוב",needs_attention:"דורש תשומת לב",critical:"צוואר בקבוק",unknown:"לא ידוע"};return <div className="health-map" role="img" aria-label="מפת הבריאות השיווקית שלך">{DIAGNOSTIC_AREAS.map((area,i)=><div key={area} className={`health-segment ${result.states[area]} ${result.primary===area?"main":""}`}><i>{result.states[area]==="healthy"?"✓":result.states[area]==="critical"?"!":result.states[area]==="unknown"?"?":"•"}</i><span><b>{AREA_LABELS[area]}</b><small>{stateText[result.states[area]]}</small></span>{i<6&&<em>←</em>}</div>)}</div>}
export default function Home(){const[started,setStarted]=useState(false),[step,setStep]=useState(0),[answers,setAnswers]=useState<AnswerRecord[]>([]),[selected,setSelected]=useState<string|null>(null),[whyOpen,setWhyOpen]=useState(false);const questions=useMemo(()=>getQuestionsForAnswers(answers),[answers]),currentQuestion=questions[step],done=step>=questions.length,result=useMemo(()=>evaluateDiagnostic(answers),[answers]);const restart=()=>{setStarted(false);setStep(0);setAnswers([]);setSelected(null);setWhyOpen(false);window.scrollTo({top:0})};const choose=(id:string)=>{if(selected||!currentQuestion)return;setSelected(id);setTimeout(()=>{setAnswers(v=>[...v,{questionId:currentQuestion.id,optionId:id}]);setStep(v=>v+1);setSelected(null);setWhyOpen(false);window.scrollTo({top:0,behavior:"smooth"})},350)};const back=()=>{if(!step){setStarted(false);return}setStep(v=>v-1);setAnswers(v=>v.slice(0,-1));setSelected(null);setWhyOpen(false)};return <main dir="rtl">
 <header className="topbar"><button onClick={restart} aria-label="חזרה להתחלה"><Mark/></button><strong>בדיקת השיווק החכם</strong></header>
 {!started?<><section className="home-hero"><div className="hero-copy"><p className="overline">אבחון אסטרטגי לעסקים קטנים</p><h1>מה באמת תוקע<br/><em>את השיווק שלך עכשיו?</em></h1><p className="lead">לא תמיד צריך עוד פוסט, עוד קמפיין או עוד כלי.<br/>לפעמים צריך לזהות איפה השיווק נתקע.<br/>האבחון הקצר הזה יעזור לך להבין במה נכון להתמקד עכשיו.</p><button className="primary-button" onClick={()=>setStarted(true)}>התחילי את האבחון <span>←</span></button><small className="meta">כ־5 דקות · בלי הרשמה · מפת פעולה אישית בסיום</small></div><div className="hero-map"><StageVisual area="focus"/><p>שבעה שלבים שמחברים בין פעילות, תוצאה וסדר עדיפויות</p></div></section><section className="value-strip"><span>אבחון ממוקד</span><span>שבעה תחומים</span><span>תוצאה אישית</span><span>מפת פעולה ל־30 יום</span></section><section className="what"><div><small>מה תקבלי בסיום</small><h2>לא עוד רשימת משימות.<br/>מפה שמראה מה קודם.</h2><button className="rose-button" onClick={()=>setStarted(true)}>התחילי עכשיו <span>←</span></button></div><ul><li>תמונת מצב מלאה</li><li>צוואר הבקבוק המרכזי</li><li>סדר פעולות ברור</li><li>תכנית אישית ל־30 יום</li></ul></section></>:
 !done&&currentQuestion?<section className="question-shell" aria-live="polite"><div className="progress-copy"><span>{currentQuestion.stage}</span><b>{currentQuestion.decision?"הבהרה קצרה":`שלב ${step+1} מתוך 7`}</b></div><div className="progress" role="progressbar" aria-valuemin={1} aria-valuemax={questions.length} aria-valuenow={step+1}><i style={{width:`${((step+1)/questions.length)*100}%`}}/></div><article className="question-card question-split"><div className="question-copy"><div className="stage-heading"><small>{currentQuestion.decision?"שאלה ממוקדת":`שלב ${step+1} מתוך 7`}</small><h2>{currentQuestion.stage}<span className="why-wrap"><button className="why-trigger" onClick={()=>setWhyOpen(v=>!v)} aria-expanded={whyOpen} aria-controls="why-bubble" aria-label="למה זה חשוב">ⓘ</button>{whyOpen&&<span className="why-bubble" id="why-bubble" role="status"><b>למה זה חשוב?</b>{currentQuestion.why}<button onClick={()=>setWhyOpen(false)} aria-label="סגירת ההסבר">×</button></span>}</span></h2></div><h1>{currentQuestion.title}</h1><div className="answers">{currentQuestion.options.map(x=><button key={x.id} className={selected===x.id?"selected":""} disabled={selected!==null} aria-pressed={selected===x.id} onClick={()=>choose(x.id)}><span>{x.label}</span><i>{selected===x.id?"✓":""}</i></button>)}</div></div><StageVisual area={currentQuestion.area}/></article><button className="back" onClick={back}>← חזרה</button></section>:
 <section className="result-dashboard"><section className="result-hero-new"><div className="diagnosis-copy"><p className="overline">האבחון שלך</p><h1>{result.headline}</h1><p>{result.summary}</p><span className="confidence">רמת ודאות: <b>{result.confidence==="HIGH"?"גבוהה":result.confidence==="MEDIUM"?"בינונית":"נדרש עוד מידע"}</b></span></div><div><h2>מפת הבריאות השיווקית שלך</h2><HealthMap result={result}/></div></section>
 <section className="snapshot"><header><small>התמונה המלאה</small><h2>תמונת המצב שלך</h2></header><div><article><i>✓</i><h3>מה עובד</h3><p>{result.whatWorks}</p></article><article className="blocked"><i>!</i><h3>מה מעכב</h3><p>{result.bottleneck}</p></article><article><i>→</i><h3>מה קודם למה</h3><p>{result.priority}</p></article></div></section>
 <section className="why"><header><small>החיבור בין התשובות</small><h2>למה זה קורה?</h2></header><p className="cause">{result.cause}</p><div>{result.evidence.length?result.evidence.map((x,i)=><article key={x}><b>0{i+1}</b><p>{x}</p></article>):<article><b>?</b><p>נדרש מידע נוסף כדי להפריד בין האפשרויות.</p></article>}</div></section>
 <section className="business-impact"><header><small>מה זה יוצר בפועל</small><h2>ההשפעה על השיווק</h2></header><ul>{result.businessImpact.map(x=><li key={x}>{x}</li>)}</ul></section>
 <section className="not-primary"><small>מה כנראה לא הבעיה המרכזית כרגע</small><h2>{result.notPrimary}</h2></section>
 <section className="diagnosis-visual"><div><small>המחשה של צוואר הבקבוק</small><h2>{result.primary?AREA_LABELS[result.primary]:"איסוף מידע"}</h2><p>{result.bottleneck}</p></div><StageVisual area={result.visual} compact/></section>
 {result.secondary&&<section className="secondary-gap"><small>נושא משני שכדאי לשים לב אליו</small><h2>יש גם סימנים שדורשים תשומת לב ב{AREA_LABELS[result.secondary]}</h2><p>אחרי שהצעד הראשון יתחיל להתייצב, אפשר לחזור גם לנושא הזה בלי לפזר את המאמץ עכשיו.</p></section>}
 <section className="action-hierarchy"><header><small>בסדר הנכון</small><h2>מפת הפעולה שלך</h2></header><ol>{result.actionMap.map((x,i)=><li key={x.label}><b>{i+1}</b><div><small>{x.label}</small><h3>{x.title}</h3><p><strong>מטרה:</strong> {x.goal}</p><p><strong>מה לעשות:</strong> {x.action}</p><p><strong>תוצר:</strong> {x.output}</p></div>{i<2&&<i>←</i>}</li>)}</ol></section>
 <section className="first-action"><div><small>הצעד הראשון שלך</small><h2>{result.firstAction}</h2></div></section>
 <section className="month-plan"><header><small>תכנית אישית לפי האבחון</small><h2>איך הייתי עובדת על זה ב־30 הימים הקרובים</h2></header><ol>{result.plan.map(x=><li key={x.week}><b>{x.week}</b><p><strong>מטרה:</strong> {x.goal}</p><p><strong>פעולה:</strong> {x.action}</p><p><strong>תוצר:</strong> {x.output}</p><p><strong>בדיקה:</strong> {x.check}</p></li>)}</ol></section>
 <section className="progress-signals"><small>איך תדעי שאת בכיוון הנכון?</small><h2>סימני התקדמות</h2><ul>{result.progressSignals.map(x=><li key={x}>{x}</li>)}</ul></section>
 <section className="avoid-now"><small>מה יכול לחכות</small><h2>כדי לשמור על המיקוד, כרגע לא צריך</h2><ul>{result.avoid.map(x=><li key={x}>{x}</li>)}</ul></section>
 <section className="final-cta"><div><small>כשהמפה ברורה, אפשר לבנות ממנה תכנית</small><h2>רוצה להפוך את האבחון הזה לתכנית שיווק מסודרת?</h2><p>נוכל לתרגם את סדר העדיפויות לתכנית שמתאימה לעסק, לזמן ולמטרות שלך.</p></div><div><a href="https://tali-digicard.vercel.app/" target="_blank" rel="noreferrer">לבניית תכנית שיווקית יחד <span>←</span></a><button onClick={restart}>אני ממשיכה לבד עם המפה</button></div></section></section>}
 <footer><Mark/><span>טלי רוזנברג<br/><small>שיווק דיגיטלי חכם לעסקים קטנים</small></span></footer></main>}
